services:
  db:
    image: postgres:16-alpine
    container_name: lavadero-postgres
    environment:
      POSTGRES_DB: lavadero
      POSTGRES_USER: lavadero_user
      POSTGRES_PASSWORD: lavadero_pass
    ports:
      - "5432:5432"
    volumes:
      - lavadero_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "lavadero_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  lavadero_pg_data:

# levantar contenedor con: docker compose up -d
# tirar contenedor con: docker compose down -v